/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './hooks/**/*.{js,jsx,ts,tsx}',
    './app/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['HankenGrotesk_400Regular', 'HankenGrotesk_600SemiBold', 'HankenGrotesk_700Bold', 'system-ui'],
        mono: ['JetBrainsMono_500Medium', 'monospace'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em' }],
        'headline-md': ['24px', { lineHeight: '32px' }],
        'headline-sm': ['20px', { lineHeight: '28px' }],
        'body-lg': ['18px', { lineHeight: '26px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        technical: ['14px', { lineHeight: '20px', letterSpacing: '0.05em' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.08em' }],
      },
      borderRadius: {
        terminal: '8px',
        card: '12px',
      },
      colors: {
        background: 'rgb(var(--background) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'surface-elevated': 'rgb(var(--surface-elevated) / <alpha-value>)',
        'surface-low': 'rgb(var(--surface-low) / <alpha-value>)',
        foreground: 'rgb(var(--foreground) / <alpha-value>)',
        'foreground-secondary': 'rgb(var(--foreground-secondary) / <alpha-value>)',
        'foreground-muted': 'rgb(var(--foreground-muted) / <alpha-value>)',
        border: 'rgb(var(--border) / 0.35)',
        input: 'rgb(var(--input) / <alpha-value>)',
        'input-border': 'rgb(var(--input-border) / <alpha-value>)',
        placeholder: 'rgb(var(--placeholder) / <alpha-value>)',
        primary: 'rgb(var(--primary) / <alpha-value>)',
        'on-primary': 'rgb(var(--on-primary) / <alpha-value>)',
        danger: 'rgb(var(--danger) / <alpha-value>)',
        'on-danger': 'rgb(var(--on-danger) / <alpha-value>)',
        emergency: 'rgb(var(--emergency) / <alpha-value>)',
        'emergency-surface': 'rgb(var(--emergency-surface) / <alpha-value>)',
        'emergency-muted': 'rgb(var(--emergency-muted) / <alpha-value>)',
        'success-banner': 'rgb(var(--success-banner) / <alpha-value>)',
        'success-banner-text': 'rgb(var(--success-banner-text) / <alpha-value>)',
        'seq-badge': 'rgb(var(--seq-badge) / <alpha-value>)',
        'seq-badge-text': 'rgb(var(--seq-badge-text) / <alpha-value>)',
        'tab-bar': 'rgb(var(--tab-bar) / <alpha-value>)',
        'tab-bar-border': 'rgb(var(--tab-bar-border) / <alpha-value>)',
        'modal-surface': 'rgb(var(--modal-surface) / <alpha-value>)',
        'modal-text': 'rgb(var(--modal-text) / <alpha-value>)',
        'modal-text-secondary': 'rgb(var(--modal-text-secondary) / <alpha-value>)',
        'modal-border': 'rgb(var(--modal-border) / <alpha-value>)',
        link: 'rgb(var(--link) / <alpha-value>)',
        'map-polyline': 'rgb(var(--map-polyline) / <alpha-value>)',
        'map-fallback': 'rgb(var(--map-fallback) / <alpha-value>)',
        'secondary-btn': 'rgb(var(--secondary-btn) / <alpha-value>)',
        'secondary-btn-text': 'rgb(var(--secondary-btn-text) / <alpha-value>)',
        'status-scheduled': 'rgb(var(--status-scheduled) / <alpha-value>)',
        'status-active': 'rgb(var(--status-active) / <alpha-value>)',
        'status-pending': 'rgb(var(--status-pending) / <alpha-value>)',
        'status-alert': 'rgb(var(--status-alert) / <alpha-value>)',
        'status-completed': 'rgb(var(--status-completed) / <alpha-value>)',
        'status-info': 'rgb(var(--status-info) / <alpha-value>)',
      },
    },
  },
  plugins: [],
};
